tap "homebrew/bundle"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# Distributed revision control system
brew "git"
# Simple terminal UI for git commands
brew "lazygit"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Platform built on V8 to build network applications
brew "node"
# Rust toolchain installer
brew "rustup-init"
# Terminal multiplexer
brew "tmux"
# JavaScript package manager
brew "yarn"
# UNIX shell (command interpreter)
brew "zsh"
# Additional completion definitions for zsh
brew "zsh-completions"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
