include colors.conf

# font
font_family RobotoMono Nerd Font Mono
font_size 10.0
modify_font cell_height 110%

# apperance
window_margin_width 10
cursor_shape block
cursor_blink_interval 0
shell_integration no-cursor

