# autostart
exec-once = hyprpaper
exec-once = waybar
exec-once = dunst
exec-once = kime

# environment variables
env = xcursor_size,24
env = hyprcursor_size,24
env = XDG_CURRENT_DESKTOP,Hyprland
env = GTK_IM_MODULE,kime
env = QT_IM_MODULE,kime
env = XMODIFIERS,@im=kime
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# monitor
monitor=,preferred,auto,1.25

# window rule
windowrulev2 = suppressevent maximize, class:.*

