general { 
    gaps_in = 10
    gaps_out = 20
    border_size = 0
}

decoration {
    drop_shadow = true
    shadow_range = 50 
    shadow_render_power = 4
    col.shadow = rgba(00000050)
    blur {
        enabled = true
        size = 10
        passes = 1
        vibrancy = 0.1696
    }
}

animations {
    enabled = true
    bezier = myBezier, 0.77, 0, 0.175, 1
    animation = windows, 1, 5, myBezier
    animation = windowsOut, 1, 5, default, popin 80%
    animation = fade, 1, 5, default
    animation = workspaces, 1, 5, default, fade
}

input {
    kb_options = korean:ralt_hangul
    follow_mouse = 2
}

cursor {
    no_hardware_cursors = true
}

xwayland {
    force_zero_scaling = true
}

