# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @plugin 'christoomey/vim-tmux-navigator'

# general
set -g mouse off
set -g default-terminal 'screen.xterm-256color'
set -g terminal-overrides ',xterm-256color:Tc'
set -g base-index 1
setw -g mode-keys vi
setw -g pane-base-index 1

# keymaps
unbind C-b
set -g prefix C-a
bind r source-file ~/.tmux.conf \; display 'tmux.conf reloaded'

# sessions
unbind s
set -g @sessionist-kill-session 'Q'
set -g @sessionist-goto 's'
set -g @sessionist-promote-pane 'no-key'
set -g @sessionist-promote-window 'no-key'
set -g @sessionist-join-pane 'no-key'

# windows
unbind w
bind c command-prompt -p 'new window name:' 'new-window; rename-window "%%"'

# panes
unbind '"'
unbind %
unbind ' '
bind v split-window -h
bind x split-window -v
bind y set-window-option synchronize-panes
bind q kill-pane
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r -T prefix C-h resize-pane -L
bind -r -T prefix C-j resize-pane -D
bind -r -T prefix C-k resize-pane -U
bind -r -T prefix C-l resize-pane -R

# pane colors
set -g pane-border-style fg='#f0f0f0'
set -g pane-active-border-style fg='#f0f0f0'

# status bar
set -g status-bg '#f0f0f0'
set -g status-fg '#585f66'
set -g status-left '#[bold] #S #[]'
set -g status-left-length 20
set -g window-status-current-format '#I #W'
set -g window-status-format '#[fg=#abb0b7]#I #W#[]'
set -g status-right '#[fg=#abb0b7]#(whoami)@#h '
set -g status-right-length 20
set -g mode-style bg='#ff9940',fg='#fafafa'
set -g message-style bg='#ff9940',fg='#fafafa'
set -g message-command-style bg='#ff9940',fg='#fafafa'

# check tpm installation and run
if 'test ! -d ~/.tmux/plugins/tpm' \
   'run "git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins"'
run '~/.tmux/plugins/tpm/tpm'

